---
authors:
- admin
categories:
- 科研
date: "2022-10-01T00:00:00Z"
draft: false
featured: false
image:
  caption: 'Link'
  focal_point: ""
  placement: 2
  preview_only: false
lastmod: "2022-10-03T00:00:00Z"
projects: []
summary: "将自己阅读近30年经济学理论文献的若干心得用自己的语言写出来  —-平新乔 "
tags:
- 微观经济学
- 笔记
title: " [教材|笔记] 微观经济学十八讲 "

output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 消费者理论
## 第一讲 偏好、效用与消费者的基本问题
**需求**的三要素：**偏好**（消费集[consumption set]或选择集[choice set]；偏好关系[preference relation]）、**价格**（相对价格）、**收入**  
* 价格+收入=预算集（可行的）  
* 偏好+预算集[budget set]=需求   

### 第一节 消费者与偏好关系    
1. 消费集 $\mathbf{X} = \mathbf{R} _{+}^{n} $   
    ① $\phi \ne \mathbf{X} \subseteq \mathbf{R} _{+}^{n}$  
    ② $\mathbf{X}$为**闭集**（所有的极限点[分析的概念，在集合中能找到一个子集以这个点为极限，或不包含该点本身的任意小的空心邻域都与集合有交集的点；单点集也是闭集]也包含在内）  
    ③ $\mathbf{X}$为**凸**（任意线性组合也包含在内）  
    ④ $0\in \mathbf{X}$ （可以选择不消费） 
2. 偏好关系 $\succeq $  （至少一样好）   
    【公理1】 完备性： 对于消费集中任意$x^{1}, x^{2}$，有$x^{1} \succeq x^{2}$ 或 $x^{2} \succeq x^{1}$ 
    【公理2】 反身性：对于消费集中所有的$x$，$x\succeq x$ (至少和本身一样好) 
    【公理3】 传递性：对于消费集中任意$x^{1}, x^{2}, x^{3}$，如果$x^{1} \succeq x^{2}$ 和 $x^{2} \succeq x^{3}$，则$x^{1} \succeq x^{3}$ （选择是一致的）   
    满足公理1、2、3的偏好关系是**理性**的（rationality）   
    【公理4】连续性：对于消费集中的任意$x$，偏好于$x$的与非偏好于$x$的集合都是闭集（不满足的例子：字典序偏好[实例：买火车票，先看时期，后看等级]）——偏好不会发生突发性的逆转     
    【公理5'】局部非餍足性：对于消费集中的所有的$x^{0}$，都有$x\in B_{\varepsilon }(x^{0})\cap \mathbf{R} _{+}^{n},(\varepsilon>0)$，则$x^{1} \succeq x^{2}$——不存在无差异区域      
    【公理5】单调性：对于消费集中的任意$x^{1}, x^{2}$，若$x^{1} \ge  x^{2}$，则$x^{1} \succeq x^{2}$；若$x^{1} \gg  x^{2}$，则$x^{1} \succ x^{2}$ ——排除了无差异曲线中斜率为正的线段    
    满足公理4、5的理性偏好关系是**自然**的    
    【公理6'】凸性：如果$x^{1} \succeq x^{0}$，对于任意$\lambda \in [0,1]$，都有$\lambda x^{1} + (1- \lambda)x^{0} \succeq x^{0}$ ——无差异曲线不能凹向原点    
    【公理6】严格凸性：——无差异曲线凸向原点    
    
### 第二节 效用函数
1. 效用函数
一个实函数$u$，当且仅当$x^{1} \succeq x^{2}$,有$u(x^{1})\ge u(x^{2})$
消费者的偏好分析——>函数的数学分析
满足存在性，不满足唯一性（效用函数的单调变换）  
2. 边际效用(MU: marginal utility)
效用函数对$x$求一阶导
3. 边际替代率(MRS: marginal rate of substitution)
对无差异曲线进行隐函数求导   
$$MRS_{i,j}(x)=\frac{\frac{\partial u(x)}{\partial x_{j}} }{\frac{\partial u(x)}{\partial x_{i}} }  $$
$i$对（对于）$j$的替代，（1单位$i$能替代几单位$j$）,$i$在分母，$j$在分子，经济学的约定俗成

### 第三节 消费者的基本问题
1. 消费者偏好的基本性质   
① 不同的无差异曲线不能相交    
② 每条无差异曲线严格凸向原点     
③ 越朝右上，无差异曲线代表的效用水平越高         

2. 预算集   
$$B=\left \{x|x \in \mathbf{R}_{+}^{n}, p\cdot x \le y \right \}$$
3. 消费者的基本问题    
给定预算集选择消费计划最大化效用函数（用拉格朗日方法求解）
解得（马歇尔）需求函数：$x_{i}=f(p,y)$ (所有商品价格和收入的函数)    
性质：   
① 物品$i$的边际效用与物品$j$的边际效用之比等于它们的价格之比$\frac{\frac{\partial u(x)}{\partial x_{j}} }{\frac{\partial u(x)}{\partial x_{i}} } = \frac{p_{j}}{p_{i}} $       
② 消费者问题存在最优解时，预算线斜率与无差异曲线的斜率相等，即共公切线   
③ 等边际法则：边际效用除以价格等于影子价格  

4. 效用函数的单调变换（序数效用论）     
从本质上看，单调变换和一个单调函数是一回事。   
例子：   
① 对原效用函数乘上一个正数   
② 对原效用函数加上任意一个数   
③ 对原效用函数取奇次幂    
④ 对数函数与指数函数互为单调变换函数    


未完待续……
 
 
 
 